### ISSUE TITLE
License of this project

### ISSUE THREAD

**Issue by Pallokala** [quicksnap/redux-guards#2]
Hi,

What is the license of this project?
Package.json mentions MIT, but proper LICENSE -file is missing. Could you add correct License -file with the intended license to the root of the project?

**Comment by quicksnap** [comment]
@Pallokala sorry about the delay on this.. I seemed to have missed the notification.

This project will have MIT. I'll upload a license in a few moments. Sorry again about the delay.. I just didn't notice!

**Comment by quicksnap** [comment]
Done!
